version: "3.9"
name: terraform
services:
  terraform:
    image: hashicorp/terraform:1.7
    volumes:
      - ${PWD}:/terraform
    working_dir: /terraform
    entrypoint: /bin/sh
    command: ["-c", "tail -f /dev/null"]
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
