version: "3.9"
name: zabbix
services:
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:6.0-alpine-latest
    restart: always
    environment:
      - DB_SERVER_HOST=pgsql-server
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    links:
      - pgsql-server

  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-pgsql:6.0-alpine-latest
    restart: always
    ports:
      - "80:8080"
    environment:
      - DB_SERVER_HOST=pgsql-server
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - ZBX_SERVER_NAME=zabbix-server
      - PHP_TZ=America/Sao_Paulo
    links:
      - pgsql-server

  pgsql-server:
    container_name: pgsql-server
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgsql-data:/var/lib/postgresql/data

volumes:
  pgsql-data:
