version: "3.9"
name: grafana
services:
  grafana-loki:
    container_name: grafana-loki
    image: grafana/loki:2.9.4
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    links:
      - grafana-web

  grafana-promtail:
    container_name: grafana-promtail
    image: grafana/promtail:2.9.4
    restart: always
    volumes:
      - log-data:/var/log
    command: -config.file=/etc/promtail/config.yml
    links:
      - grafana-web

  grafana-web:
    container_name: grafana-web
    image: grafana/grafana:10.3.1
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

volumes:
  log-data: