version: "3.9"
name: zabbix
services:
  zabbix-server:
    container_name: zabbix-server
    build: ./zabbix-server-pgsql
    restart: always
    environment:
      - DB_SERVER_HOST=zabbix-pgsql
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    links:
      - zabbix-pgsql
    ports:
      - "10051:10051"
    volumes:
      - zabbix-data:/var/lib/zabbix


  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-pgsql:6.0-alpine-latest
    restart: always
    ports:
      - "8081:8080"
    environment:
      - DB_SERVER_HOST=zabbix-pgsql
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - ZBX_SERVER_NAME=zabbix-server
      - PHP_TZ=America/Sao_Paulo
    links:
      - zabbix-pgsql
    volumes:
      - zabbix-data:/var/lib/zabbix

  zabbix-pgsql:
    container_name: zabbix-pgsql
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgsql-data:/var/lib/postgresql/data

volumes:
  pgsql-data:
  zabbix-data: