name: Duplicate PR to Testing

on:
  pull_request:
    branches:
      - main

jobs:
  duplicate_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Duplicate PR to Testing
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          PR_NUMBER=$(echo "$GITHUB_REF" | awk -F/ '{print $3}')
          git fetch origin pull/$PR_NUMBER/head:testing-PR-$PR_NUMBER
          git push origin testing-PR-$PR_NUMBER --force-with-lease=testing-PR-$PR_NUMBER
